version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: daaiki/main
    working_dir: /works
    volumes:
      - .:/works
      - node_modules_volume:/works/node_modules:delegated
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  node_modules_volume: